<a href="https://colab.research.google.com/github/RubenMcCarty/Python-for-Data-Science-AI/blob/main/Secci%C3%B3n_02_Fundamentals_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **What is a List**
# MSc: Ruben Quispe

In [1]:
MyFirstList =[3, 45, 56, 732]

In [2]:
MyFirstList

[3, 45, 56, 732]

In [3]:
type(MyFirstList)

list

In [4]:
l2 = ['Hello', 24, True, 55.3]

In [5]:
l2

['Hello', 24, True, 55.3]

In [6]:
l3 = ['How are you', 55, MyFirstList]

In [7]:
l3

['How are you', 55, [3, 45, 56, 732]]

In [8]:
range(0, 15)

range(0, 15)

In [9]:
list(range(15)) # esto es en python 3 .... en python 2 es xrange()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [10]:
x = [1,2,3,4,5,6,7]

In [11]:
x

[1, 2, 3, 4, 5, 6, 7]

In [12]:
y = list(range(8))

In [13]:
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [14]:
z = list(range(1,8))

In [15]:
z

[1, 2, 3, 4, 5, 6, 7]

In [16]:
z2 = list(range(100,120))

In [17]:
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [18]:
w = list(range(100,111,2))

In [19]:
w

[100, 102, 104, 106, 108, 110]

In [20]:
w2 = list(range(100,201,10))

In [21]:
w2

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

# **Using the [] brackets**

In [22]:
w = ['a', 'b', 'c', 'd', 'e']

In [23]:
w

['a', 'b', 'c', 'd', 'e']

In [24]:
w[0]

'a'

In [25]:
w[1]

'b'

In [26]:
w[2]

'c'

In [27]:
len(w)

5

In [28]:
w[4]

'e'

In [29]:
w

['a', 'b', 'c', 'd', 'e']

In [30]:
# 0    1    2     3    4
#-5   -4   -3    -2   -1

In [31]:
w[-1] # diferente comportamiento para retornar

'e'

In [32]:
w[-2]

'd'

In [33]:
w[-3]

'c'

In [34]:
w

['a', 'b', 'c', 'd', 'e']

In [35]:
w[2] = 63

In [36]:
w

['a', 'b', 63, 'd', 'e']

In [37]:
# lygometry


# **Slicing**

In [38]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [39]:
letters


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [40]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [41]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [42]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [43]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [44]:
letters[-8:7]

['C', 'D', 'E', 'F', 'G']

In [45]:
letters[-8:-3]

['C', 'D', 'E', 'F', 'G']

In [46]:
# advanced slicing

In [47]:
letters [2:9:2]

['C', 'E', 'G', 'I']

In [48]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [49]:
letters[::3]

['A', 'D', 'G', 'J']

# **Tuples in Python**

In [50]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [51]:
letters[2:7:1]

['C', 'D', 'E', 'F', 'G']

In [52]:
letters[2:7:-1]

[]

In [53]:
letters[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [54]:
letters[6:1:-2]

['G', 'E', 'C']

In [55]:
# Tuple = inmutable list


In [56]:
t1 = [345, 647, 934]

In [57]:
t1

[345, 647, 934]

In [58]:
t1[1]

647

In [59]:
t1[0]

345

In [60]:
t1[1]= 45

In [61]:
t1

[345, 45, 934]

# **Funtions in Python**

In [62]:
range(20, 31)

range(20, 31)

In [63]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [64]:
mylist1 = list(range(20,31))

In [65]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [66]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [67]:
len(mylist1)

11

In [68]:
type(mylist1)

list

In [69]:
max(mylist1)

30

In [70]:
min(mylist1)

20

In [71]:
max(11, 435, 7)

435

# **Packages in Python**

In [72]:
!conda install scrapy

/bin/bash: conda: command not found


In [73]:
import scrapy

ModuleNotFoundError: ignored

In [74]:
from scrapy.crawler import CrawlerProcess

ModuleNotFoundError: ignored

# **Arrays in python**

In [78]:
import numpy as np


In [75]:
l = [2345, 26, 657, 234, -1234]

In [81]:
a = np.array(l)

In [82]:
a

array([ 2345,    26,   657,   234, -1234])

In [80]:
b = np.array(['12', '455', '63.3', 'True', 'abc'])

In [83]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U4')

In [84]:
l.pop()

-1234

In [86]:
l

[2345, 26, 657, 234]

In [85]:
a.mean()

405.6

# **Slicing Arrays**

In [87]:
a

array([ 2345,    26,   657,   234, -1234])

In [88]:
l

[2345, 26, 657, 234]

In [89]:
l[0:2]

[2345, 26]

In [90]:
l[::2]

[2345, 657]

In [91]:
a 

array([ 2345,    26,   657,   234, -1234])

In [92]:
a[2:]

array([  657,   234, -1234])

In [93]:
a[2:4]

array([657, 234])

In [94]:
b = a[2:4]

In [95]:
b

array([657, 234])

In [96]:
b[0]

657

In [97]:
b[:]

array([657, 234])

In [99]:
b

array([657, 234])

In [98]:
a

array([ 2345,    26,   657,   234, -1234])

In [100]:
c = a.copy()

In [101]:
c

array([ 2345,    26,   657,   234, -1234])

In [103]:
c[0] = 0

In [104]:
c


array([    0,    26,   657,   234, -1234])

In [105]:
a

array([ 2345,    26,   657,   234, -1234])

# Section Recap
1. what is list?
2. Created some list:[], range()
3. Using the [] brackets
4. Slicing list
5. Tuples
6. Functions in R
7. Packages in R
8. Numpy and arrays
9. Slicing Arrays